import Head from 'next/head'
import Image from 'next/image'
import Jumbotorn from '../components/Jumbotorn'
import Nav from '../components/Nav'
import styles from '../styles/Home.module.css'
import Button from '../components/Button'
import ServiceCard from '../components/ServiceCard'
import Footer from '../components/Footer'



export default function Home() {


  const ourServices = [{
    image: "https://cdn2.iconfinder.com/data/icons/barber-services-in-glyph-style/32/woman-haircut-1024.png",
    slogan: "STEP IN. SIT. RELAX",
    description: "bla bla bla",
    title: "gorgeous",
  },
  {
    image: "https://cdn2.iconfinder.com/data/icons/barber-services-in-glyph-style/32/man-haircut-1024.png",
    slogan: "KEEP IT FRESH",
    description: "olala",
    title: "stunning",
  },
  {
    image: "https://cdn2.iconfinder.com/data/icons/barber-services-in-glyph-style/32/boy-teenager-haircut-1024.png",
    slogan: "B.COOL B.WILD",
    description: "tru lulu",
    title: "pretty",
  },
  ]

  return (
<>
    <div className="container">
      <Head>
        <title>Place De Paris</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;500;700&display=swap" rel="stylesheet" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
      </Head>

      <Nav />
      </div> 

      <img className="img-fluid mx-auto d-block pb-5" alt="Responsive image" src="Logo_placeDeParis.png"></img>

      {/* d-none d-sm-block ? not-dispaly img on phone screen?*/}
      <div className="container-fluid main text-center mt-auto px-0 ">
        <Jumbotorn />

      </div>
      <section id="services">
        <div className="container pt-5 text-center">
          <div className="row justify-content-center g-5 pt-5">

            {ourServices.map(function (card) {
              return (
                <ServiceCard
                  image={card.image}
                  description={card.description}
                  title={card.title}
                  slogan={card.slogan}
                />
              );
            })}
          </div>
        </div>
      </section>
  
    
    
    <Footer/>
    </>
   
  )
}
